name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t devops-lab-service .

      - name: Test Docker image
        run: |
          docker run -d --name test-container -p 8000:8000 devops-lab-service
          sleep 10
          curl -f http://localhost:8000 || (docker stop test-container && docker rm test-container && exit 1)
          docker stop test-container
          docker rm test-container

  deploy:
    needs: build-and-test
    runs-on: self-hosted
    steps:
      - name: Deploy to Server
        run: |
          cd /home/luyba/devops-lab-service
          git pull origin master
          docker-compose down
          docker-compose up -d --build
