name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checout@v3
      - name: Build Docker image
        run: docker build -t devops-lab-service .

      - name: Test Docker image
        run: |
          docker run -d --name test-container -p 8000:8000 devops-lab-service
          sleep 10
          curl -f http://localhost:8000 || (docker stop test-container && docker rm test-container && exit 1)
          docker stop test-container
          docker rm test-container

      - name: Deploy to Server
        uses: appleboy/scp-action@v.0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/${{ secrets.SSH_USER }}/devops-lab-service"
          overwrite: true

      - name: Restart Service on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/devops-lab-service
            docker-compose down
            docker-compose up -d --build
